// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvdrheyazebfqphinque.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZHJoZXlhemViZnFwaGlucXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjcwNDUsImV4cCI6MjA2NDcwMzA0NX0.Ah3w1oH_az6kApxPJbXt3EgEeeH8LFcroU58qoprtJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);